- name: Infra.mac playbook
  hosts: localhost
  gather_facts: false
  connection: local
  environment:
    # 未設定の場合、/opt/homebrew-cask/Caskroomになる
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  tasks:
    - name: Tap a Homebrew repository
      community.general.homebrew_tap:
        name: [
          'possatti/possatti', # pokemonsay
          'pulumi/tap',        # pulumi
          # 'keyclu',        # KeyClu
        ]
    - name: Install homebrew packages
      community.general.homebrew:
        name: [
          # common
          'git', 'git-secrets',
          'jq', 'nkf',
          'yq',
          'wget',
          'tree',
          'openssl',
          'vim', 'neovim',
          'tmux', 'tmuxinator',
          'zoxide',
          # extend
          'bat', 'eza', 'fd',
          'coreutils', 'gnu-sed', 'gawk', 'findutils', 'xz',
          'fzf', 'expect', 'mise', 'gpg', 'gnupg',
          # etc
          'opentofu',                                         # IaC
          'readline', 'reattach-to-user-namespace',           # terminal
          'awscli',                                           # aws
          'kubectl', 'kind', 'kubecolor', 'k9s', 'helm',      # k8s
          'docker', 'docker-compose', 'docker-completion',    # docker
          'toilet',                                           # ascii
          'uv',                                               # python
          'delve',                                            # golang
          'alp', 'graphviz', 'mysql-client',                  # for isucon
          # tap
          'pokemonsay',
          'pulumi/tap/pulumi', 'pulumi/tap/esc',              # IaC
          'keyclu'
        ]
        state: present
        update_homebrew: yes
    
    - name: Install Krew
      script: "{{ playbook_dir }}/scripts/install_krew.sh"
    - name: Install Krew plugins
      shell: "kubectl krew install {{ item }}"
      with_items:
        - stern
        - ctx
        - ns
        - rolesum
        - access-matrix
        - cost

    - name: Install Rust by rustup
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Install Starship
      shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
    - name: Install SDKMAN
      shell: curl -s "https://get.sdkman.io" | bash -s -- -y
