- name: Infra.mac playbook
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: Set XDG environment variables if not defined
      set_fact:
        xdg_data_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(lookup('env', 'HOME') + '/.local/share') }}"
        xdg_config_home: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(lookup('env', 'HOME') + '/.config') }}"

    - name: Show XDG environment variables
      debug:
        msg:
          - "XDG_DATA_HOME: {{ xdg_data_home }}"
          - "XDG_CONFIG_HOME: {{ xdg_config_home }}"

  tasks:
    - name: Include Homebrew tasks
      import_tasks: tasks/homebrew.yml
    - name: Include Language installation tasks
      import_tasks: tasks/langs.yml
    - name: Include Tools tasks
      import_tasks: tasks/tools.yml
